///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConcentricityBasler1inch
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ConcentricityBasler1inchRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("cceee3c0-7f37-4740-90a1-215a33ebfe7e")]
    public partial class ConcentricityBasler1inchRepository : RepoGenBaseFolder
    {
        static ConcentricityBasler1inchRepository instance = new ConcentricityBasler1inchRepository();
        ConcentricityBasler1inchRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;

        /// <summary>
        /// Gets the singleton class instance representing the ConcentricityBasler1inchRepository element repository.
        /// </summary>
        [RepositoryFolder("cceee3c0-7f37-4740-90a1-215a33ebfe7e")]
        public static ConcentricityBasler1inchRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ConcentricityBasler1inchRepository() 
            : base("ConcentricityBasler1inchRepository", "/", null, 0, false, "cceee3c0-7f37-4740-90a1-215a33ebfe7e", ".\\RepositoryImages\\ConcentricityBasler1inchRepositorycceee3c0.rximgres")
        {
            _snapxuntitled = new ConcentricityBasler1inchRepositoryFolders.SnapXUntitledAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cceee3c0-7f37-4740-90a1-215a33ebfe7e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("b4937d61-8cd2-4fdc-9377-b645a582f265")]
        public virtual ConcentricityBasler1inchRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class ConcentricityBasler1inchRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("b4937d61-8cd2-4fdc-9377-b645a582f265")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _finishInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 30000, null, true, "b4937d61-8cd2-4fdc-9377-b645a582f265", "")
            {
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "element[@controlid='94']", 30000, null, "120cb71d-a0f2-471e-b77a-e9430ff5548c");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[@controlid='59648']/form//button[@text='&OK']", 120000, null, "28ccb800-e37d-4889-aee1-948551ba538b");
                _finishInfo = new RepoItemInfo(this, "Finish", "container[@controlid='59648']/form//button[@text='Finish' and @enabled='True']", 240000, null, "7ea703cf-87dc-4d77-8737-63bf27154fee");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b4937d61-8cd2-4fdc-9377-b645a582f265")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b4937d61-8cd2-4fdc-9377-b645a582f265")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("120cb71d-a0f2-471e-b77a-e9430ff5548c")]
            public virtual Ranorex.Unknown TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("120cb71d-a0f2-471e-b77a-e9430ff5548c")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("28ccb800-e37d-4889-aee1-948551ba538b")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("28ccb800-e37d-4889-aee1-948551ba538b")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("7ea703cf-87dc-4d77-8737-63bf27154fee")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("7ea703cf-87dc-4d77-8737-63bf27154fee")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}